### ISSUE TITLE
Git integration needed for environments

### ISSUE THREAD

**Issue by matthewhillesheim** [launchiamenterprise/keyrunner#13]
Environments are vital for collab work between teams, I hope this was just an oversite to not include this in Git.

I see that collections and playgrounds are enabled with GIT but not environments...

**Comment by launchiamenterprise** [comment]
We deliberately ignored environment variables in the Git push because they often contain sensitive information like secret keys and API keys. Including them could pose a security risk.

We are still collecting feedback and will come up with a secure solution for handling environment variables when pushing them to git.

**Comment by launchiamenterprise** [comment]
@matthewhillesheim  As a work around we have introduced exporting environment variables with v1.0.50 for team collaboration.
