### ISSUE TITLE
Not able to enter a variable for a GraphQL query

### ISSUE THREAD

**Issue by kristenkinnearohlmann** [launchiamenterprise/keyrunner#25]
I am testing as part of the KeyRunner demo for Mayo Clinic.

I am not able to determine how to add a variable for my GraphQL request. I tried using Prescript, but the tool appeared to go into an infinite loop.

I would have expected to find a Variable tab to enter my variables.

I did check the documentation but was not able to find information under the GraphQL entry.

I am using version 1.0.50 on Windows.

**Comment by launchiamenterprise** [comment]
@kristenkinnearohlmann can you try collapsing the response tab and see if you are able to see variables tab ? 
<img width="718" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/8f91b0e4-b90e-40d5-897b-3b80d436c00d">


Currently scripting is in beta phase and we are trying to fix those issues. Infinite loop issue has been identified and we will release a minor version this weekend to fix the issue. We will also release documentation on usage of scripting.

**Comment by launchiamenterprise** [comment]
@kristenkinnearohlmann  We changed the variables and query CSS in graphql tab to be side-by-side instead of vertical alignment. Is this the issue you were referring to, or is it something else?

<img width="733" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/0f96feef-01e9-4a0f-8e24-fba7afd8bf73">


Here’s the documentation for scripting: 
https://docs.keyrunner.app/docs/scripting.html

**Comment by kristenkinnearohlmann** [comment]
By collapsing the response tab, I was able to see the variables tab. I
don't see an option for displaying them side by side, which I would prefer,
so I will watch for an update.
