### ISSUE TITLE
Data being retained when uninstalling/ reinstalling

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#53]
**Describe the bug**
When uninstalling and reinstalling, KeyRunner still contains old test suites and environment variables.

**To Reproduce**
Uninstall
Reinstall

**Expected behavior**
When reinstalling, expecting KeyRunner to be a blank slate. (no old test suites, variables, etc)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [1.0.63]

**Additional context**
Is there a way to just wipe the data? Or is manually removing the only option?

Thank you!

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management The current behavior of retaining test suites and environment variables after reinstallation is intentional. Most users prefer not to lose their data when updating or reinstalling the application to avoid having to reconfigure everything from scratch.

To completely wipe the data delete all the files and folders from this location : 
C:\Users\{{user}}\AppData\Roaming\Code\User\globalStorage\keyrunner-lite-by-liam
